version: '3.8'

services:
  degreed-ui:
    build:
      context: .
      dockerfile: degreed-take-home-ui/Dockerfile
    image: degreed-ui:latest
    container_name: degreed-ui
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - REDIS_CONNECTION=redis:6379
    restart: unless-stopped
    networks:
      - degreed-network
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    container_name: degreed-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - degreed-network

networks:
  degreed-network:
    driver: bridge

volumes:
  redis-data: