services:
  degreed-ui:
    build:
      context: .
      dockerfile: degreed-take-home-ui/Dockerfile
    image: degreed-ui:latest
    container_name: degreed-ui
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    restart: unless-stopped
    networks:
      - degreed-network

networks:
  degreed-network:
    driver: bridge